version: '3.3'
services:
  docker-mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
      
  my-jpa-app:
    image: img-grader
    depends_on:
      - docker-mysql
    ports:
      - 8082:8081

